version: '3.8'

services:
  anki_db:
    container_name: anki_database_django
    image: postgres
    env_file:
      - ".env"
    environment:
      POSTGRES_PASSWORD: $PASSWORD_DB
      POSTGRES_USER: $USER_DB
      POSTGRES_DB: $NAME_DB
    restart: always
    ports:
     - "5432"
    networks:
      - botnet
    volumes:
      - ./postgresql:/var/lib/postgresql

  anki:
    container_name: django_anki
    build:
      context: .
    command:  bash -c "poetry run python manage.py makemigrations && poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - "8000:8000"
    networks:
      - botnet
    restart: always
    env_file:
      - ".env"
    depends_on:
      - anki_db


networks:
  botnet:

    driver: bridge