# Generated by Django 4.1.4 on 2022-12-29 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='decks.decks')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='styles.styles')),
            ],
        ),
    ]
