# Generated by Django 4.1.4 on 2022-12-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='answer_type',
            field=models.CharField(choices=[('md', 'Markdown'), ('text', 'Text'), ('html', 'HTML')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='cards',
            name='question_type',
            field=models.CharField(choices=[('md', 'Markdown'), ('text', 'Text'), ('html', 'HTML')], default='text', max_length=10),
        ),
    ]
