# Generated by Django 4.1.4 on 2022-12-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cards_answer_type_cards_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='easiness',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='interval',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='repetitions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='review_date',
            field=models.DateField(null=True),
        ),
    ]
