# Generated by Django 4.1.4 on 2023-01-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_cards_easiness_cards_interval_cards_repetitions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='random_num',
            field=models.IntegerField(null=True),
        ),
    ]
